global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: blazekv
    metrics_path: /metrics
    static_configs:
      - targets: ["blazekv:9121"]
        labels:
          service: blazekv
